import {LABELS, RECIPES, BASKETS, CHAPTERS, REGULARS, CARDS} from './core.mjs';

export const VI = {
  'Ingredients · {0}/{1}': 'Nguyên liệu · {0}/{1}', 'Any two · one cup': 'Hai nguyên liệu · một ly',
  'House blend': 'Ly pha sáng tạo', 'House blend: {0}': 'Ly pha sáng tạo: {0}',
  'Try new pairs anywhere on the table.': 'Thử ghép các nguyên liệu bất kỳ trên bàn.',
  'Banana and cocoa are on the table. Sora and Leo are coming by.': 'Chuối và ca cao đã có trên bàn. Sora và Leo sắp ghé quán.',
  'Blueberry, orange and tea are on the table. Noor is on her way.': 'Việt quất, cam và trà đã có trên bàn. Noor đang tới.',
  'Peach, honey and matcha are on the table. Someone special is coming.': 'Đào, mật ong và matcha đã có trên bàn. Một vị khách đặc biệt sắp đến.',
  'Drag two different ingredients into the cup, then stop the marker in green.': 'Kéo hai nguyên liệu khác nhau vào ly, rồi dừng vạch trong vùng xanh.',
  'Empty the mixing cup': 'Làm trống ly pha chế', 'Taste timing': 'Canh vị ngon', 'Green = best taste': 'Vùng xanh = ngon nhất',
  'Drop here': 'Thả vào đây', 'One more': 'Thêm một món', 'Ready to mix': 'Sẵn sàng pha', 'Pouring…': 'Đang rót…',
  'Mixing cup: {0} of 2 ingredients. {1}': 'Ly pha chế: {0}/2 nguyên liệu. {1}',
  'Stop & save': 'Dừng & cất ly', 'Stop & pour': 'Dừng & rót', '+5 taste bonus': '+5 xu vị ngon', 'Add 2 ingredients': 'Thêm 2 nguyên liệu',
  'Perfect taste! ★': 'Ngon tuyệt! ★', 'A lovely cup!': 'Một ly thơm ngon!', 'Tap when it is green': 'Chạm khi vạch vào xanh', 'Fill the cup first': 'Thêm nguyên liệu vào ly',
  'Ready! Stop the marker in green.': 'Xong rồi! Dừng vạch trong vùng xanh.',
  '{0} is in the cup. Add one more.': 'Đã thêm {0}. Thêm một nguyên liệu nữa nhé.',
  'A green hit adds 5 coins. Every other cup still earns money.': 'Dừng trong vùng xanh được thêm 5 xu. Ly khác vẫn bán được tiền.',
  'Drop inside the cup, or tap an ingredient.': 'Thả vào trong ly, hoặc chạm vào nguyên liệu.',
  'Drag or tap two different ingredients into the cup.': 'Kéo hoặc chạm để thêm hai nguyên liệu khác nhau vào ly.',
  'Add those two ingredients to the cup.': 'Thêm hai nguyên liệu đó vào ly.',
  'Drag the strawberry and milk into the center cup.': 'Kéo dâu tây và sữa vào ly ở giữa.',
  'Add {0} and {1} to the cup.': 'Thêm {0} và {1} vào ly.',
  'Fill the cup to make a drink for later.': 'Thêm nguyên liệu vào ly để pha sẵn.',
  'The cup is empty. Try a fresh pair.': 'Ly đã trống. Hãy thử một cặp nguyên liệu mới.',
  '{0}{1}. Drag into the cup, or tap to add.': '{0}{1}. Kéo vào ly hoặc chạm để thêm.',
  'Perfect taste: +5 when served.': 'Vị ngon tuyệt: thêm 5 xu khi phục vụ.',
  'Language': 'Ngôn ngữ', 'Lantern Street': 'Phố Đèn Lồng', 'Auntie Rosa': 'Dì Rosa',
  'Petal Café game': 'Trò chơi Petal Café', 'Golden hour meter': 'Tiến độ giờ vàng', 'Coins': 'Xu',
  'Turn sound off': 'Tắt âm thanh', 'Turn sound on': 'Bật âm thanh',
  'Your café on Lantern Street': 'Quán cà phê của bạn trên Phố Đèn Lồng',
  'Petal Café, a warm little café diorama': 'Petal Café, quán cà phê nhỏ ấm cúng',
  'Mina, helping behind the counter': 'Mina đang phụ việc sau quầy', 'Auntie Rosa, home for the festival': 'Dì Rosa trở về dự lễ hội',
  'Guests waiting': 'Khách đang chờ', 'Golden hour · ×2': 'Giờ vàng · ×2', 'Selected guest': 'Khách đang chọn', 'Friendship': 'Tình bạn',
  'Mixing table: drag an ingredient onto another, or tap two ingredients.': 'Bàn pha chế: kéo nguyên liệu này vào nguyên liệu khác, hoặc chạm vào hai nguyên liệu.',
  'Ingredient baskets': 'Giỏ nguyên liệu', 'Return ingredients to their places': 'Đưa nguyên liệu về vị trí ban đầu',
  'Make-ahead shelf. Matching orders serve automatically.': 'Kệ đồ uống pha sẵn. Tự động phục vụ khi có khách gọi đúng món.',
  'Three saved drinks': 'Ba chỗ để đồ uống pha sẵn', 'Saved cups serve matches': 'Tự phục vụ khi đúng món',
  'Current chapter': 'Chương hiện tại', 'Open the book for this chapter': 'Mở sổ của chương này', 'Open ›': 'Mở ›', 'Chapter progress': 'Tiến độ chương',
  'Café extras': 'Sổ tay của quán', 'Recipes': 'Công thức', 'Letters': 'Thư', 'Everything you have poured': 'Những món bạn đã pha',
  'Close recipe book': 'Đóng sổ công thức', 'Recipe book': 'Sổ công thức', "Auntie Rosa's recipe box": 'Hộp công thức của dì Rosa',
  'Each card is a riddle about one pair. Mix that pair to solve it.': 'Mỗi thẻ là một câu đố về hai nguyên liệu. Pha đúng cặp để giải đố.',
  'Letters from Lantern Street': 'Thư từ Phố Đèn Lồng', 'Close letters': 'Đóng thư', 'Continue': 'Tiếp tục', 'Lantern lit': 'Đã thắp đèn',
  'This café is open in another tab': 'Quán đang mở ở tab khác',
  'Your progress is safe. Continue here to pause the other tab, or close it and try again.': 'Tiến độ của bạn vẫn an toàn. Chọn chơi tại đây để tạm dừng tab kia, hoặc đóng tab kia rồi thử lại.',
  'Continue in this tab': 'Chơi tại tab này', 'Connecting…': 'Đang kết nối…',
  'Close the other tab, then try again.': 'Hãy đóng tab kia rồi thử lại.',
  'Golden hour: {0} doubled cups left': 'Giờ vàng: còn {0} ly được nhân đôi tiền',
  'Golden hour meter: {0} of {1} favorites': 'Tiến độ giờ vàng: {0}/{1} món đúng ý khách',
  'Mina is on her break': 'Mina đang nghỉ', 'Mina · +10 every 20s': 'Mina · +10 xu/20 giây', 'All lanterns lit': 'Đã thắp sáng mọi đèn', 'Made with love': 'Pha bằng cả tấm lòng',
  '{0} would love {1}.': '{0} muốn gọi {1}.', 'this mystery cup': 'ly bí ẩn này', 'a mystery cup': 'một ly bí ẩn',
  'Bring the two ingredients together.': 'Ghép hai nguyên liệu lại với nhau.',
  'Read the cup: its colors hint at the ingredients.': 'Quan sát màu sắc của ly để đoán nguyên liệu.',
  '{0} wants {1}. {2}': '{0} gọi {1}. {2}', 'First in line.': 'Đứng đầu hàng.', ' · home for the festival': ' · về dự lễ hội',
  'Mystery cup': 'Ly bí ẩn', 'Show pair': 'Gợi ý', 'Peek': 'Xem thử',
  'Highlight the ingredients for {0}': 'Làm nổi bật nguyên liệu của món {0}',
  'Peek at the ingredients (no guessing bonus)': 'Xem nguyên liệu (không nhận thưởng đoán đúng)',
  ', highlighted': ', đang được gợi ý', '{0}{1}. Drag onto another ingredient, or tap to select.': '{0}{1}. Kéo vào nguyên liệu khác hoặc chạm để chọn.',
  'All {0} lanterns lit': 'Đã thắp sáng {0} đèn lồng', 'Every night is lantern night': 'Đêm nào cũng rực rỡ đèn lồng',
  'Recipes {0}/{1} · Best friends {2}/6 · Cards {3}/{4}': 'Món {0}/{1} · Bạn thân {2}/6 · Thẻ {3}/{4}',
  'Lantern {0} of {1}': 'Đèn lồng {0}/{1}', 'Ready!': 'Sẵn sàng!', '{0} to go': 'Còn thiếu {0}', '{0} for {1} coins': '{0} với {1} xu',
  'Make ahead': 'Pha sẵn', 'Serve now': 'Phục vụ ngay', 'Tap to serve now': 'Chạm để phục vụ ngay', 'Tap to make ahead': 'Chạm để pha sẵn',
  '{0}. Tap to serve; matching orders serve automatically.': '{0}. Chạm để phục vụ; tự phục vụ khi khách gọi đúng món.',
  'Empty preparation space {0}': 'Chỗ pha sẵn số {0} còn trống', 'Save a drink for later': 'Để dành đồ uống cho khách sau',
  'Four ingredients, six pairings. Your guests keep their places in line.': 'Bốn nguyên liệu, sáu cách ghép. Khách vẫn giữ chỗ trong hàng.',
  'Drag the {0} onto the {1}.': 'Kéo {0} vào {1}.', '✨ Something new…': '✨ Một món mới…',
  'Your shelf is full.': 'Kệ pha sẵn đã đầy.', 'Tap a saved cup to serve it, or switch to Serve now.': 'Chạm vào một ly trên kệ để bán, hoặc chuyển sang Phục vụ ngay.',
  'Auntie Rosa is waiting for her Lantern latte.': 'Dì Rosa đang chờ latte đèn lồng.',
  'Only that cup will do. Read her recipe card in the book.': 'Dì chỉ muốn món ấy thôi. Hãy xem thẻ công thức của dì trong sổ.',
  '{0} saved for later.': 'Đã để dành {0}.', 'Matching guests get it automatically. Tap a saved cup to serve anyone.': 'Tự phục vụ khi khách gọi đúng món. Chạm vào ly trên kệ để bán cho khách bất kỳ.',
  "{0}'s favorite! +{1}{2}{3}": 'Đúng món {0} thích! +{1}{2}{3}', ' · golden ×2': ' · giờ vàng ×2', ' · sharp eye!': ' · tinh mắt!',
  'New recipe: {0}': 'Công thức mới: {0}', '{0} for {1}. +{2}': '{0} cho {1}. +{2}',
  'New recipe: {0}. Not quite their order, but they are happy.': 'Công thức mới: {0}. Chưa đúng món gọi nhưng khách vẫn vui.',
  'Not their favorite, but every cup counts.': 'Chưa đúng món yêu thích, nhưng ly nào cũng có giá trị.',
  'Best friends! A gift of {0} coins.': 'Đã thành bạn thân! Bạn nhận được {0} xu.', 'Friendship grew to ♥{0}.': 'Tình bạn tăng lên ♥{0}.',
  'Recipe card solved: “{0}”. +{1} coins': 'Đã giải thẻ “{0}”. +{1} xu', 'Golden hour! The next 5 cups pay double.': 'Giờ vàng! Năm ly tiếp theo được nhân đôi tiền.',
  'Ready right on time! Favorite tip included.': 'Sẵn sàng đúng lúc! Có thêm tiền boa vì đúng món.', 'Every saved cup earns coins.': 'Mỗi ly trên kệ đều bán được xu.',
  'The riddles are in the recipe book.': 'Các câu đố nằm trong sổ công thức.', 'Hearts are shown in Letters.': 'Xem trái tim tình bạn trong mục Thư.',
  'Try new pairs in every basket.': 'Thử các cặp nguyên liệu mới trong từng giỏ.', 'Every five favorites fill the sun.': 'Cứ năm món đúng ý khách sẽ làm đầy mặt trời.', 'Read the cups in the line.': 'Quan sát các ly khách đang gọi.',
  'Lantern {0} of {1} lit': 'Đã thắp đèn lồng {0}/{1}', 'A gift of {0} coins.': 'Bạn nhận được {0} xu.', 'Next lantern: {0}.{1}': 'Đèn tiếp theo: {0}.{1}',
  'Petal Café is yours. Keep pouring, every night is lantern night.': 'Petal Café đã là của bạn. Cứ tiếp tục pha chế để đêm nào cũng sáng đèn lồng.',
  'Undiscovered': 'Chưa khám phá', 'Locked': 'Chưa mở', 'Unlocks with: {0}': 'Mở khi: {0}',
  '{0}: {1}. Highlight on the table.': '{0}: {1}. Gợi ý nguyên liệu trên bàn.', ' and ': ' và ',
  'Serve it to anyone, or to the guest who ordered it for a tip.': 'Bán cho khách bất kỳ, hoặc đúng khách gọi món để nhận tiền boa.',
  'not yet': 'chưa gặp', 'Lantern {0}': 'Đèn lồng {0}', '♥{0} with {1}': '♥{0} với {1}',
  'Letters arrive as you light lanterns and make friends.': 'Thư sẽ đến khi bạn thắp đèn và kết bạn.',
  'Your table, just the way you like it.': 'Bày bàn theo cách bạn thích.', 'Drop an ingredient onto another to make a drink.': 'Thả nguyên liệu này vào nguyên liệu khác để pha đồ uống.',
  'Pick any two ingredients.': 'Chọn hai nguyên liệu bất kỳ.', '{0} selected. Tap another ingredient.': 'Đã chọn {0}. Chạm vào một nguyên liệu khác.',
  'Make a cup for later.': 'Pha một ly để dành.', 'Back to serving your guests.': 'Tiếp tục phục vụ khách.', 'Three spaces. Matching orders serve automatically.': 'Ba chỗ trên kệ. Tự phục vụ khi khách gọi đúng món.',
  'Every drink earns coins. Favorites add a tip.': 'Món nào cũng có xu. Đúng món khách thích sẽ có tiền boa.', 'A fresh little table.': 'Bàn pha chế đã gọn gàng.', '{0}: done!': '{0}: hoàn tất!',
  'The bakery basket is open. Sora and Leo are coming by.': 'Đã mở giỏ tiệm bánh. Sora và Leo sắp ghé quán.',
  'The garden basket is open. Noor is on her way.': 'Đã mở giỏ vườn. Noor đang tới.', 'The lantern basket is open. Someone special is coming.': 'Đã mở giỏ đèn lồng. Một vị khách đặc biệt sắp đến.',
  'Your prep shelf is open. Make ahead for the line of three!': 'Đã mở kệ pha sẵn. Pha trước cho hàng ba vị khách nhé!', 'Mina is making coffees on her own.': 'Mina đang tự pha cà phê để phụ bạn.',
  'Mina kept the café going: +{0} coins.': 'Mina đã trông quán giúp bạn: +{0} xu.', 'Up to five minutes of earnings while you were away.': 'Tích lũy tối đa năm phút thu nhập khi bạn vắng mặt.',
  'Your café is open. Saving is unavailable in this browser.': 'Bạn vẫn có thể chơi, nhưng trình duyệt này không lưu được tiến độ.',
  'Welcome back! Your café moved to Lantern Street.': 'Mừng bạn trở lại! Quán đã chuyển tới Phố Đèn Lồng.',
  'Coins, renovations, recipes and friendships came with you.': 'Xu, nâng cấp, công thức và tình bạn đều được giữ lại.',
  'Mina would love a strawberry milk.': 'Mina muốn một ly sữa dâu.', 'Drag the glowing strawberry onto the milk.': 'Kéo quả dâu đang sáng vào sữa.',
  'A letter from the seaside': 'Lá thư từ miền biển', 'The key is under the flowerpot': 'Chìa khóa ở dưới chậu hoa',
  'Light all twelve lanterns before the Lantern Festival.': 'Thắp sáng cả mười hai đèn lồng trước Lễ hội Đèn Lồng.',
  'Welcome back to Lantern Street.': 'Mừng bạn trở lại Phố Đèn Lồng.', 'Mina earned {0} coins while you were away.': 'Mina kiếm được {0} xu khi bạn vắng mặt.', 'Your guests are waiting.': 'Khách đang đợi bạn.',
};

const ingredients = {strawberry:'Dâu tây', mango:'Xoài', milk:'Sữa', coffee:'Cà phê', banana:'Chuối', cocoa:'Ca cao', blueberry:'Việt quất', orange:'Cam', tea:'Trà', peach:'Đào', honey:'Mật ong', matcha:'Matcha'};
for (const [id, value] of Object.entries(ingredients)) VI[LABELS[id]] = value;
const drinks = {
  'strawberry-milk':['Sữa dâu','Béo vị sữa, hồng vị dâu.'], 'mango-milk':['Sữa xoài','Béo vị sữa, vàng vị xoài.'],
  latte:['Latte cà phê','Béo vị sữa, đậm cà phê, với hình trái tim bên trên.'],
  'strawberry-brew':['Cà phê ủ lạnh dâu','Đậm cà phê bên trên, hồng vị dâu bên dưới.'],
  'mango-brew':['Cà phê ủ lạnh xoài','Đậm cà phê bên trên, vàng vị xoài bên dưới.'],
  'sunrise-smoothie':['Sinh tố bình minh','Hồng vị dâu hòa cùng vàng vị xoài.'],
  'banana-milk':['Sữa chuối','Béo vị sữa, vàng dịu vị chuối.'], 'hot-chocolate':['Sô cô la nóng','Béo vị sữa, thơm ca cao, thêm kẹo dẻo.'],
  'banana-brew':['Cà phê ủ lạnh chuối','Đậm cà phê bên trên, vàng dịu vị chuối bên dưới.'],
  mocha:['Mocha cà phê','Đậm cà phê và ca cao dưới lớp kem bông.'],
  'banana-cocoa-shake':['Sữa lắc chuối ca cao','Ca cao bên dưới, vàng dịu vị chuối bên trên.'],
  'blueberry-milk':['Sữa việt quất','Béo vị sữa, tím vị việt quất.'], 'orange-cream':['Cam sữa béo','Béo vị sữa, tươi vị cam.'],
  'bubble-tea':['Trà sữa trân châu','Béo vị sữa, thơm trà, thêm trân châu.'],
  'blueberry-tea':['Trà việt quất','Thơm trà, tím vị việt quất, thêm bạc hà.'], 'orange-tea':['Trà cam','Thơm trà, tươi vị cam.'],
  'twilight-smoothie':['Sinh tố hoàng hôn','Tím việt quất hòa cùng cam tươi.'],
  'peach-milk':['Sữa đào','Béo vị sữa, hồng vị đào.'], 'honey-milk':['Sữa mật ong','Béo vị sữa, óng vàng mật ong.'],
  'matcha-latte':['Latte matcha','Matcha xanh bên dưới, sữa béo bên trên.'], 'peach-matcha':['Matcha đào','Matcha xanh phủ trên đào hồng.'],
  'lantern-latte':['Latte đèn lồng','Mật ong óng vàng, matcha xanh: món dì Rosa thích.'],
  'honey-peach-fizz':['Soda đào mật ong','Mật ong óng vàng, đào hồng và bọt sủi.'],
};
for (const r of RECIPES) { const v = drinks[r.art.slice(6)]; if (!v) throw Error('Missing Vietnamese recipe: ' + r.key); VI[r.name] = v[0]; VI[r.clue] = v[1]; }
for (const [id, label] of Object.entries({sunrise:'Bình minh',bakery:'Tiệm bánh',garden:'Khu vườn',lantern:'Đèn lồng'})) {
  VI[BASKETS[id].short] = label; VI[BASKETS[id].name] = 'Giỏ ' + label.toLowerCase();
}
const chapters = {
  shutters: ['Mở cửa quán', 'Phục vụ 3 ly', null, 'Chìa khóa ở dưới chậu hoa. Máy pha đã cũ hơn cả cháu, biển hiệu cũng bạc màu rồi. Nhưng cứ mở cửa và pha ba ly nhé. Con phố này vẫn nhớ hương vị ngày xưa.'],
  sign: ['Biển hiệu cho Phố Đèn Lồng', 'Sơn biển hiệu', 'Sơn biển hiệu', 'Ôi, PETAL CAFÉ mở lại rồi! Tôi sẽ báo cho mọi người trên tuyến giao hàng. Mai quán sẽ đông khách lắm đấy.'],
  cups: ['Đọc vị những ly nước', 'Pha đúng 6 món khách thích', null, 'Giờ chỉ cần nhìn ly là bạn biết chúng tôi muốn gì rồi. Dì Rosa cũng làm được thế. Dì treo một chiếc đèn bên cửa sổ cho mỗi vị khách quen.'],
  bench: ['Chỗ ngồi cho bác thợ bánh', 'Thêm ghế dài', 'Thêm ghế', 'Một chiếc ghế dài tử tế đấy. Được rồi, tôi mang chuối và ca cao đến, vì rõ ràng quán này cần một bác thợ bánh.'],
  box: ['Hộp công thức của dì', 'Giải 2 thẻ công thức', null, 'Hộp thiếc sau quầy đựng các thẻ công thức của Rosa. Bà ấy viết thành câu đố để tôi không chép được. Giải chúng đi, quán sẽ lại thơm như ngày xưa.'],
  golden: ['Giờ vàng', 'Kích hoạt giờ vàng', null, 'Khi nắng chiếu qua cửa sổ vừa đúng góc, cả quán bừng sáng. Rosa gọi đó là giờ vàng, và món gì cũng ngon gấp đôi.'],
  mina: ['Hai chiếc tạp dề', 'Mời Mina phụ quán', 'Thuê Mina', 'Bạn cứ pha những món đầy màu sắc, để cà phê đơn giản cho tôi. Tôi cũng đang dành tiền mua màu vẽ áp phích lễ hội!'],
  garden: ['Cổng vườn của Hana', 'Mở khu vườn', 'Mở vườn', 'Việt quất, cam và một ấm trà mới mỗi sáng. Noor ở vườn cộng đồng muốn gặp bạn đấy!'],
  menu: ['Thực đơn phong phú', 'Khám phá 16 công thức', null, 'Mười sáu công thức rồi! Rosa từng dán một danh sách như thế trên tủ lạnh. Tôi tìm thấy nó trong nhà kho ngoài vườn. Nét chữ của bạn vừa khéo nối tiếp nét chữ của dì.'],
  friends: ['Bạn bè Phố Đèn Lồng', 'Đạt ♥3 với cả 6 khách quen', null, 'Mọi người lại háo hức nói về lễ hội. Tôi có bài hát, Noor có giấy, Jun có thiệp mời. Chỉ còn thiếu một nơi để tụ họp thôi.'],
  terrace: ['Hiên đèn lồng', 'Xây hiên quán', 'Xây hiên', 'Đào từ cây của Hana, mật ong từ đàn ong của tôi, matcha từ trên đồi. À! Có một lá thư gửi từ miền biển đến…'],
  festival: ['Lễ hội Đèn Lồng', 'Mời dì Rosa latte đèn lồng', null, 'Dì đã thấy những chiếc đèn từ trên xe buýt. Cửa sổ nào trên phố cũng sáng rực. Cháu không chỉ mở lại một quán cà phê, cháu đã thắp sáng cả con phố. Giữ chìa khóa nhé. Quán là của cháu rồi.'],
};
for (const c of CHAPTERS) { const v = chapters[c.id]; VI[c.title] = v[0]; VI[c.task] = v[1]; if (c.action) VI[c.action] = v[2]; VI[c.letter] = v[3]; }
const people = {
  mina: ['Họa sĩ minh họa', 'Trước kia tôi vẽ đèn lồng mỗi mùa thu. Từ ngày quán đóng cửa, cuốn sổ vẽ của tôi cứ để trống.', 'Tôi đang vẽ áp phích lễ hội. Cho tôi đặt quán của bạn ngay giữa tranh nhé?', ['“Đúng vị tôi thích!”','“Tôi phải vẽ món này vào sổ mới được.”','“Bạn vẫn nhớ!”']],
  jun: ['Người giao hàng bằng xe đạp', 'Dì Rosa cho tôi công việc đầu tiên: giao ca cao tới tiệm bánh. Lúc ấy tôi mới tám tuổi.', 'Tôi sẽ đạp xe mang thiệp mời lễ hội tới từng nhà trên đồi. Không bỏ sót ai cả.', ['“Có sức leo đồi rồi!”','“Tuyệt lắm, tôi đi đây!”','“Điểm dừng tuyệt nhất trên tuyến!”']],
  hana: ['Người bán trái cây', 'Rosa luôn mua những quả đào méo mó. Dì bảo: “Chúng ngọt nhất đấy.” Dì nói đúng thật.', 'Tôi trồng một cây đào sau sạp hàng. Lễ hội năm sau, món nào cũng có đào nhé!', ['“Nắng ấm trong một chiếc ly!”','“Trái cây của tôi chưa bao giờ ngon thế.”','“Ôi, màu đẹp quá!”']],
  sora: ['Thợ làm bánh', 'Tôi và dì bạn tranh luận về ca cao suốt hai mươi năm. Dì ấy đúng. Đừng nói với dì nhé.', 'Tìm thấy sau lò nướng cũ của tôi: một thẻ công thức của dì. Chắc dì giấu tôi đấy.', ['“Ừm. Gần ngon bằng tôi làm.”','“Ngon hơn bánh sừng bò của tôi. Gần thôi.”','“Rosa sẽ hài lòng đấy.”']],
  leo: ['Thầy dạy nhạc', 'Mỗi mùa lễ hội, cả phố hát một bài dưới những chiếc đèn lồng. Tôi quên mất nửa lời rồi.', 'Tôi nhớ ra lời hai rồi! Bài hát kể về một ô cửa nhỏ luôn mở.', ['“Đúng nốt rồi!”','“Hoan hô!”','“Âm nhạc trong một chiếc cốc.”']],
  noor: ['Người làm vườn', 'Giấy đèn lồng làm từ vỏ cây dâu. Tôi đã trồng vài cây trong vườn, biết đâu có lúc cần.', 'Cây dâu đã sẵn sàng. Đủ giấy làm đèn lồng cho cả con phố rồi.', ['“Tươi như sương sớm!”','“Khu vườn gửi lời cảm ơn!”','“Thật tươi sáng và đáng yêu!”']],
};
for (const [id, p] of Object.entries(REGULARS)) {
  const v = people[id]; VI[p.role] = v[0]; VI[p.beats[2]] = v[1]; VI[p.beats[4]] = v[2];
  p.thanks.forEach((text, i) => { VI[text] = v[3][i]; });
}
const cards = {
  cloud:['Mây hồng','Một đám mây hồng rót vào bữa sáng.'], sunrise:['Ly cà phê bình minh','Mặt trời mọc trên hạt cà phê sẫm màu.'],
  baker:['Bí mật của bác thợ bánh','Nâu hòa cùng nâu, đội một nụ cười vàng.'], night:['Bầu trời đêm','Ngâm thật chậm cả bầu trời đêm.'],
  dusk:['Nơi hoàng hôn bắt đầu','Nơi ráng chiều gặp những vì sao đầu tiên.'], lantern:['Ánh sáng bên cửa sổ','Vàng từ đàn ong, xanh từ ngọn đồi.'],
};
for (const c of CARDS) { VI[c.title] = cards[c.id][0]; VI[c.riddle] = cards[c.id][1]; }
